### ISSUE TITLE
Button not appearing sometimes after switching pages

### ISSUE THREAD

**Issue by uncenter** [uncenter/npm-on-github#6]
Is the MutationObserver failing to process the page?

**Comment by PatrickJS** [comment]
yeah it's not showing up for me but I'm also on Brave browser

**Comment by uncenter** [comment]
Hmm at all? What GitHub page are you expecting it to appear on?

**Comment by uncenter** [comment]
If you are talking about https://github.com/PatrickJS/node-everything, it's because the latest version of the package on NPM has this in the package.json:

```json
  "repository": {
    "type": "git",
    "url": "https://github.com/gdi2290/node-everything.git"
  },
```

Which doesn't match the current status of the repo under your account. If you can figure out how to get past the 10mb limit and publish it, it shouldn't have any issues anymore.

**Comment by PatrickJS** [comment]
oh yeah, actually all the repos I checked it on wasn't on npm haha I see it now. yeah I can't publish a new version because there's a 10mb package limit but I did fix that in latest

**Comment by PatrickJS** [comment]
oh I guess this issue can be updated for mono repos where it's not showing up
https://github.com/BuilderIO/qwik

**Comment by uncenter** [comment]
Ooh true I hadn't considered that. I'll have to somehow find all of the package.json files in the repository... and which one would I link to / get stats for If there are multiple packages?

**Comment by PatrickJS** [comment]
yeah I guess the ui will have to change to show multiple packages. and you can default show the one with the most downloads

**Comment by uncenter** [comment]
yeah i think ill show multiple graphs for all packages found. and the number on the button will be all of them added up or smt
